### ISSUE TITLE
Error script build-s3-dist.sh

### ISSUE THREAD

**Issue by donotpush** [awslabs/real-time-insights-account-activity#3]
The getting started/installation script of this project does not work. 

```
Generating web site manifest
./build-s3-dist.sh: line 51: cd: /Users/xxx/projects/real-time-insights-account-activity/deployment/manifest-generator: No such file or directory
npm WARN saveError ENOENT: no such file or directory, open '/Users/xxx/projects/real-time-insights-account-activity/source/update_ddb_from_stream/dist/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/xxx/projects/real-time-insights-account-activity/source/update_ddb_from_stream/dist/package.json'
npm WARN dist No description
npm WARN dist No repository field.
npm WARN dist No README data
npm WARN dist No license field.

up to date in 0.69s
found 0 vulnerabilities

internal/modules/cjs/loader.js:605
    throw err;
    ^

Error: Cannot find module '/Users/xxx/projects/real-time-insights-account-activity/source/update_ddb_from_stream/dist/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
(aws) ➜  deployment git:(master) ✗```

**Comment by georgebearden** [comment]
This issue should have been resolved in the latest version.
